### ISSUE TITLE
从nacos获取配置

### ISSUE THREAD

**Issue by reesezxf** [KcangYan/nacos-python-sdk#5]
`nacos_server.config(dataId="python-demo.json", group="dev", tenant="python", myConfig=config)`
这段代码 是只能生效一次吗， 如果web APP想随时从nacos拉去配置，是要写个 while 循环这样，一直执行上面这行代码吗

**Comment by reesezxf** [comment]
哦 可以动态更新config

**Comment by KcangYan** [comment]
是的 这个方法就是把你加载进来的dict对象去映射远程nacos配置中心里的json，而且会起一个线程去监听nacos配置中心的配置变化，一旦发生变化这个线程会把你装进去的dict对象同步更新。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KcangYan/nacos-python-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 晚上9:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [KcangYan/nacos-python-sdk] 从nacos获取配置 (Issue #5)





 
哦 可以动态更新config
