### ISSUE TITLE
nacosBalanceClient 负载均衡消费者示例 不太懂

### ISSUE THREAD

**Issue by reesezxf** [KcangYan/nacos-python-sdk#6]
请问作者 
`nacosClient = nacos.nacosBalanceClient(ip=nacosIp, port=nacosPort,
                                       serviceName="python-provider",
                                       group="dev", namespaceId="python")`
这里的serviceName 是生产者的服务，那这个代码是在消费者服务里定义的吗
还是说 @nacosClient.customRequestClient 装饰器只是在 这个 python-provider服务启动多个时候，调用此服务的接口时候 自动负载均衡

**Comment by KcangYan** [comment]
负载均衡方法是给消费者去调用服务提供者时 使用的 所以当然是定义在消费者端的代码里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KcangYan/nacos-python-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 晚上9:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[KcangYan/nacos-python-sdk] nacosBalanceClient 负载均衡消费者示例 不太懂 (Issue #6)





 
请问作者
 nacosClient = nacos.nacosBalanceClient(ip=nacosIp, port=nacosPort, serviceName="python-provider", group="dev", namespaceId="python")
 这里的serviceName 是生产者的服务，那这个代码是在消费者服务里定义的吗

**Comment by reesezxf** [comment]
多谢作者回复，自己搞个例子跑了一下，了解了，微服务的负载均衡一般是在客户端
